### ISSUE TITLE
sdaophot is expected in PATH, configure executable name/path in ~/pydaophot.cfg

### ISSUE THREAD

**Issue by augucarv** [majkelx/astwro#18]
I am not being able to run the Daophot whatsoever. I've change the pydaophot.cfg to account for the directury of my executables (my daophot running directory), as follows:
```

# Patches (optional) and names of executables
[executables]
daophot = ~/usr/daophot4
allstar = ~/usr/daophot4
```
but nothing changes. I've tried to copy the executables to astwro/pydaophot and rename them to 'sdaophot' and 'sallstar', but the error keeps appearing.

With a clean install, I'm not even able to reproduce the examples in the readthedocs. 
I've also tried to redirect the executables by using

```
from astwro.pydaophot import daophot_cfg
daophot_cfg.set('executables', 'daophot', '/usr/local/bin/daophot')
```

but I get the `error cannot import name 'daophot_cfg' from 'astwro.pydaophot' `. Any help is much appreciated.

Using Python 3.x in a Ubuntu 20.04.

**Comment by majkelx** [comment]
I'm sorry, the documentation left behind the codebase.
Now, there is new config files schema common for all astwro, see: https://astwro.readthedocs.io/en/latest/installation.html#configuration
for updated doc.

Thanks for finding an issue.
